BookShopExample/Controllers/BookShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookShopExample.Controllers
{
    public class BookShopController : Controller
    {
        // GET: BookShop

        private Models.BookShopDB db = new Models.BookShopDB();

        public ActionResult Index(int categoryId = -1, long bookId = -1)
        {
            var info = new Models.BookShopInfo()
            { 
                CategoryId = categoryId, 
                BookId = bookId,
            };
           
            return View(info);
        }

        public ActionResult BookList(int categoryId)
        {
            var books = db.Books;
            var categories = db.BookCategories;

            ViewBag.Categories = categories;

            

            return (categoryId != -1) ?
                    PartialView(books.OrderBy(a => a.Name).Where(a => a.Category == categoryId)) :
                    PartialView(books.OrderBy(a => a.Name));
        }

        [HttpGet]
        public ActionResult Choose(long bookId)
        {
            var chosenBook = db.Books.SingleOrDefault(a => a.BookId == bookId);
            ViewBag.ChosenBook = chosenBook;
            return PartialView();
        }

        [HttpPost]
        public ActionResult Choose(Models.Purchase purchase)
        {
            var chosenBook = db.Books.SingleOrDefault(a => a.BookId == purchase.BookFid);
            ViewBag.ChosenBook = chosenBook;
            return PartialView(purchase);
        }

        [HttpPost]
        public ActionResult Buy(Models.Purchase purchase)
        {
            var chosenBook = db.Books.Single(a => a.BookId == purchase.BookFid);
            ViewBag.ChosenBook = chosenBook;
            
            
            if (ModelState.IsValid)
            {
                ViewBag.CustomerName = purchase.CustomerName;
                chosenBook.Amount--;
                db.SaveChanges();
                return View();
            }
            else
            {
                //return View("Choose", new Models.Purchase() { BookFid = purchase.BookFid });
                return View("Index", new Models.BookShopInfo()
                {
                    CategoryId = -1,
                    BookId = purchase.BookFid,
                });
            }
           
        }
    }
}

BookShopExample/Views/BookShop/BookList.cshtml
@model IEnumerable<BookShopExample.Models.Book>

<div class="col-md-3 list-group">
    <h3 class="h3">Жанры</h3>
    @foreach (var item in ViewBag.Categories)
    {
        <div class="list-group-item">
            @{
                string name = item.Name;
                string link = "/Index/";
            }
            @Html.ActionLink(name, link, new { categoryId = item.CategoryId })
        </div>
    }

</div>
<div class="col-md-9">
    <div class="row">
        @foreach (BookShopExample.Models.Book item in Model)
        {

            <div class="col-xl-2 col-lg-3 col-md-4 col-6 card book-item">
                <input type="hidden" value="@item.BookId" />
                <div class="book-image">
                    <img src="@item.Image" alt="@item.Author - @item.Name" class="card-img-top" />
                </div>
                <div class="card-body book-info">
                    <p class="book-name text-center lead text-wrap">@item.Name</p>
                    <p class="book-author text-center">@item.Author</p>
                    <p class="book-price text-center">@item.Price грн</p>
                    <p class="book-amount">Осталось на складе: @item.Amount</p>
                    @if (item.Amount > 0)
                    {
                        @Html.ActionLink("Купить", "Index", new { bookId = item.BookId })
                    }
                    else
                    {
                        <p class="out-of-stock">Нет в наличии</p>
                    }
                </div>
            </div>

        }
    </div>
</div>

BookShopExample/Views/BookShop/Buy.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Buy</title>
</head>
<body>
    <div> 
        <p>Спасибо за покупку, @ViewBag.CustomerName!</p>
        <p>Ваш заказ, "@ViewBag.ChosenBook.Name" (@ViewBag.ChosenBook.Author) отправлен в обработку. Мы свяжемся с вами позже.</p>
        @Html.ActionLink("Вернутся на главную страницу", "Index")
    </div>
</body>
</html>

BookShopExample/Views/BookShop/Choose.cshtml
@model BookShopExample.Models.Purchase


@using (Html.BeginForm("Buy", "BookShop", FormMethod.Post, new { @class = "buy-form" }))
{
    if (ViewBag.ChosenBook.Amount > 0)
    {
        <img src="@ViewBag.ChosenBook.Image" alt="@ViewBag.ChosenBook.Name" />
        @Html.ValidationSummary();
        @Html.Hidden("BookFid", (long)ViewBag.ChosenBook.BookId);
        @Html.Label("Ваше имя: ");
        @Html.TextBoxFor(x => x.CustomerName);
        @Html.Label("Ваш телефон: ");
        @Html.TextBoxFor(x => x.CustomerPhone);


        <input type="submit" name="Заказать" />

    }
    else
    {
        <p>К сожалению, данный товар закончился. Приносим свои извинения за неудобства.</p>

    }
    <button type="button" onclick="ShowForm(false)">Х</button>

}

BookShopExample/Views/BookShop/Index.cshtml
@model BookShopExample.Models.BookShopInfo
@{
    Layout = null;
}



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Contents/css/main.css" />
    <link href="~/Contents/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Contents/js/BookShopScripts.js"></script>
    <title>Index</title>
</head>
<body>
    <div class="container-fluid">

        <div class="row">
            <div class="col">
                @if (Model.IsBuyFormVisible == true)
                {
                    Html.RenderAction("Choose", new { bookId = Model.BookId });
                }
            </div>
        </div>

        <div class="row">
            @{Html.RenderAction("BookList", new { categoryId = Model.CategoryId}); }
        </div>
    </div>



    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="~/Contents/js/bootstrap.min.js"></script>

    
        <script>
            $(document).ready(function () {
                @if (Model.IsBuyFormVisible == true) {
                    @:ShowForm(true);
                }
                else {
                    @:ShowForm(false);
                }
            });
        </script>
    


</body>
</html>